// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqsfBfbLenSIqOZxMPpevJgbhcr9RrM9c',
    appId: '1:154336934364:web:67e489619b2a2b404b7719',
    messagingSenderId: '154336934364',
    projectId: 'wintonmapapp',
    authDomain: 'wintonmapapp.firebaseapp.com',
    storageBucket: 'wintonmapapp.appspot.com',
    measurementId: 'G-KWCY1QELPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhGmYOX5J-zb0CDt_xBCRg3ZYC7Tdjy2c',
    appId: '1:154336934364:android:7623f5fbcbde28c74b7719',
    messagingSenderId: '154336934364',
    projectId: 'wintonmapapp',
    storageBucket: 'wintonmapapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNq0mqBUD6-QJ9LpKkIWyu37Iw1radvcs',
    appId: '1:154336934364:ios:7fa2c721b87326e94b7719',
    messagingSenderId: '154336934364',
    projectId: 'wintonmapapp',
    storageBucket: 'wintonmapapp.appspot.com',
    iosClientId: '154336934364-092q99vettq8indtdvghvejkr2hkimv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.winton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNq0mqBUD6-QJ9LpKkIWyu37Iw1radvcs',
    appId: '1:154336934364:ios:7fa2c721b87326e94b7719',
    messagingSenderId: '154336934364',
    projectId: 'wintonmapapp',
    storageBucket: 'wintonmapapp.appspot.com',
    iosClientId: '154336934364-092q99vettq8indtdvghvejkr2hkimv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.winton',
  );
}
